baseURL = "http://brandonsdevblog.me/"
languageCode = "en-us"
title = "Brandon's Dev Blog"
theme = "hugo-theme-bootstrap4-blog"
copyright = "© Brandon Powell 2018"

[params]
    author = "Brandon Powell"
    custom_navbar = true
    sharingicons = false
